export const EDITABLE_RUNTIME_KEYS = [
    'NEXT_PUBLIC_AMAP_API_KEY',
    'NEXT_PUBLIC_AMAP_SECURITY_CODE',
    'NEXT_PUBLIC_IFLYTEK_IAT_APP_ID',
    'NEXT_PUBLIC_IFLYTEK_IAT_API_KEY',
    'NEXT_PUBLIC_IFLYTEK_IAT_API_SECRET',
    'NEXT_PUBLIC_IFLYTEK_IAT_URL',
    'NEXT_PUBLIC_IFLYTEK_IAT_SAMPLE_RATE',
    'NEXT_PUBLIC_IFLYTEK_IAT_CHUNK_BYTES',
    'NEXT_PUBLIC_IFLYTEK_IAT_MAX_BYTES',
    'NEXT_PUBLIC_IFLYTEK_IAT_LANGUAGE',
    'NEXT_PUBLIC_IFLYTEK_IAT_DOMAIN',
    'NEXT_PUBLIC_IFLYTEK_IAT_ACCENT',
    'NEXT_PUBLIC_IFLYTEK_IAT_DWA',
    'NEXT_PUBLIC_BAILIAN_API_KEY',
    'NEXT_PUBLIC_BAILIAN_API_BASE_URL',
    'NEXT_PUBLIC_BAILIAN_DEFAULT_MODEL',
    'NEXT_PUBLIC_BAILIAN_TRIP_REQUEST_MODEL',
    'NEXT_PUBLIC_BAILIAN_TRIP_PLAN_MODEL',
    'NEXT_PUBLIC_BAILIAN_REQUEST_TIMEOUT_MS'
] as const

export type RuntimeConfigKey = (typeof EDITABLE_RUNTIME_KEYS)[number]

export type RuntimeConfig = Partial<Record<RuntimeConfigKey, string>>
